# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'casier_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(622, 507)
        self.label_erreur_numero_casier = QtWidgets.QLabel(Dialog)
        self.label_erreur_numero_casier.setEnabled(True)
        self.label_erreur_numero_casier.setGeometry(QtCore.QRect(30, 110, 441, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_erreur_numero_casier.setFont(font)
        self.label_erreur_numero_casier.setObjectName("label_erreur_numero_casier")
        self.lineEdit_numero_casier = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_numero_casier.setGeometry(QtCore.QRect(30, 60, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.lineEdit_numero_casier.setFont(font)
        self.lineEdit_numero_casier.setObjectName("lineEdit_numero_casier")
        self.label_numero_casier = QtWidgets.QLabel(Dialog)
        self.label_numero_casier.setGeometry(QtCore.QRect(30, 20, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_numero_casier.setFont(font)
        self.label_numero_casier.setObjectName("label_numero_casier")
        self.comboBox_localisation = QtWidgets.QComboBox(Dialog)
        self.comboBox_localisation.setGeometry(QtCore.QRect(30, 330, 281, 41))
        self.comboBox_localisation.setObjectName("comboBox_localisation")
        self.comboBox_localisation.addItem("")
        self.comboBox_localisation.addItem("")
        self.comboBox_localisation.addItem("")
        self.comboBox_casier = QtWidgets.QComboBox(Dialog)
        self.comboBox_casier.setGeometry(QtCore.QRect(30, 230, 281, 41))
        self.comboBox_casier.setObjectName("comboBox_casier")
        self.comboBox_casier.addItem("")
        self.comboBox_casier.addItem("")
        self.comboBox_casier.addItem("")
        self.pushButton_casier = QtWidgets.QPushButton(Dialog)
        self.pushButton_casier.setGeometry(QtCore.QRect(30, 430, 281, 51))
        self.pushButton_casier.setObjectName("pushButton_casier")
        self.label_erreur_numero_casier_2 = QtWidgets.QLabel(Dialog)
        self.label_erreur_numero_casier_2.setEnabled(True)
        self.label_erreur_numero_casier_2.setGeometry(QtCore.QRect(30, 160, 441, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_erreur_numero_casier_2.setFont(font)
        self.label_erreur_numero_casier_2.setObjectName("label_erreur_numero_casier_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_erreur_numero_casier.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ff0000;\">*Le numero de casier est doit etre composer de </span><span style=\" font-family:\'Arial,sans-serif\'; color:#ff5500;\">c</span><span style=\" font-family:\'Arial,sans-serif\'; color:#ff0000;\">omposé</span></p><p><span style=\" font-family:\'Arial,sans-serif\'; color:#ff0000;\">  d’une lettre et suivi de 4 chiffres. ex: (A0000)</span></p></body></html>"))
        self.label_numero_casier.setText(_translate("Dialog", "Numéro de casier"))
        self.comboBox_localisation.setItemText(0, _translate("Dialog", "A"))
        self.comboBox_localisation.setItemText(1, _translate("Dialog", "B"))
        self.comboBox_localisation.setItemText(2, _translate("Dialog", "C"))
        self.comboBox_casier.setItemText(0, _translate("Dialog", "Petit"))
        self.comboBox_casier.setItemText(1, _translate("Dialog", "Moyen"))
        self.comboBox_casier.setItemText(2, _translate("Dialog", "Grand"))
        self.pushButton_casier.setText(_translate("Dialog", "PushButton"))
        self.label_erreur_numero_casier_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ff0000;\">*Le numero de casier n\'est pas disponible</span></p></body></html>"))
